// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: comments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, dollar_1 sql.NullInt32) error {
	_, err := q.db.ExecContext(ctx, deleteComment, dollar_1)
	return err
}

const editComment = `-- name: EditComment :one
UPDATE comments
SET content = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, news_item_id, user_id, parent_comment_id, content, created_at, updated_at
`

type EditCommentParams struct {
	Column1 sql.NullInt32
	Column2 sql.NullString
}

type EditCommentRow struct {
	ID              int32
	NewsItemID      sql.NullInt32
	UserID          uuid.NullUUID
	ParentCommentID sql.NullInt32
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) EditComment(ctx context.Context, arg EditCommentParams) (EditCommentRow, error) {
	row := q.db.QueryRowContext(ctx, editComment, arg.Column1, arg.Column2)
	var i EditCommentRow
	err := row.Scan(
		&i.ID,
		&i.NewsItemID,
		&i.UserID,
		&i.ParentCommentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, news_item_id, user_id, parent_comment_id, content, created_at, updated_at FROM comments
WHERE id = $1
`

type GetCommentByIDRow struct {
	ID              int32
	NewsItemID      sql.NullInt32
	UserID          uuid.NullUUID
	ParentCommentID sql.NullInt32
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetCommentByID(ctx context.Context, dollar_1 sql.NullInt32) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, dollar_1)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.NewsItemID,
		&i.UserID,
		&i.ParentCommentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentsByPostID = `-- name: GetCommentsByPostID :many
SELECT id, news_item_id, user_id, parent_comment_id, content, created_at, updated_at FROM comments
WHERE news_item_id = $1
ORDER BY created_at ASC
`

type GetCommentsByPostIDRow struct {
	ID              int32
	NewsItemID      sql.NullInt32
	UserID          uuid.NullUUID
	ParentCommentID sql.NullInt32
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetCommentsByPostID(ctx context.Context, dollar_1 sql.NullInt32) ([]GetCommentsByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPostID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByPostIDRow
	for rows.Next() {
		var i GetCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.NewsItemID,
			&i.UserID,
			&i.ParentCommentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByUserID = `-- name: GetCommentsByUserID :many
SELECT id, news_item_id, user_id, parent_comment_id, content, created_at, updated_at FROM comments
WHERE user_id = $1
ORDER BY created_at ASC
`

type GetCommentsByUserIDRow struct {
	ID              int32
	NewsItemID      sql.NullInt32
	UserID          uuid.NullUUID
	ParentCommentID sql.NullInt32
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetCommentsByUserID(ctx context.Context, dollar_1 uuid.NullUUID) ([]GetCommentsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByUserID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByUserIDRow
	for rows.Next() {
		var i GetCommentsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.NewsItemID,
			&i.UserID,
			&i.ParentCommentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postComment = `-- name: PostComment :one
INSERT INTO comments (id, news_item_id, user_id, parent_comment_id, content)
VALUES (DEFAULT, $1, $2, $3, $4)
RETURNING id, news_item_id, user_id, parent_comment_id, content, created_at, updated_at
`

type PostCommentParams struct {
	Column1 sql.NullInt32
	Column2 uuid.NullUUID
	Column3 sql.NullInt32
	Column4 sql.NullString
}

type PostCommentRow struct {
	ID              int32
	NewsItemID      sql.NullInt32
	UserID          uuid.NullUUID
	ParentCommentID sql.NullInt32
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) PostComment(ctx context.Context, arg PostCommentParams) (PostCommentRow, error) {
	row := q.db.QueryRowContext(ctx, postComment,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i PostCommentRow
	err := row.Scan(
		&i.ID,
		&i.NewsItemID,
		&i.UserID,
		&i.ParentCommentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
