// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, martial_art_id, title, date, location, description FROM events
WHERE date >= NOW()
ORDER BY date ASC
`

type GetAllEventsRow struct {
	ID           int32
	MartialArtID int32
	Title        string
	Date         time.Time
	Location     string
	Description  sql.NullString
}

func (q *Queries) GetAllEvents(ctx context.Context) ([]GetAllEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEventsRow
	for rows.Next() {
		var i GetAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.MartialArtID,
			&i.Title,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByMartialArtID = `-- name: GetEventsByMartialArtID :many
SELECT id, martial_art_id, title, date, location, description FROM events
WHERE martial_art_id = $1 AND date >= NOW()
ORDER BY date ASC
`

type GetEventsByMartialArtIDRow struct {
	ID           int32
	MartialArtID int32
	Title        string
	Date         time.Time
	Location     string
	Description  sql.NullString
}

func (q *Queries) GetEventsByMartialArtID(ctx context.Context, dollar_1 sql.NullInt32) ([]GetEventsByMartialArtIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByMartialArtID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByMartialArtIDRow
	for rows.Next() {
		var i GetEventsByMartialArtIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MartialArtID,
			&i.Title,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
