// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package database

import (
	"context"
	"database/sql"
)

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, martial_art_id, title, date, location, description FROM events
ORDER BY date ASC
`

type GetAllEventsRow struct {
	ID           int32
	MartialArtID int32
	Title        string
	Date         sql.NullTime
	Location     sql.NullString
	Description  sql.NullString
}

func (q *Queries) GetAllEvents(ctx context.Context) ([]GetAllEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEventsRow
	for rows.Next() {
		var i GetAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.MartialArtID,
			&i.Title,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByMartialArtID = `-- name: GetEventsByMartialArtID :many
SELECT id, martial_art_id, title, date, location, description FROM events
WHERE martial_art_id = $1
ORDER BY date ASC
`

type GetEventsByMartialArtIDRow struct {
	ID           int32
	MartialArtID int32
	Title        string
	Date         sql.NullTime
	Location     sql.NullString
	Description  sql.NullString
}

func (q *Queries) GetEventsByMartialArtID(ctx context.Context, dollar_1 sql.NullInt32) ([]GetEventsByMartialArtIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByMartialArtID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByMartialArtIDRow
	for rows.Next() {
		var i GetEventsByMartialArtIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MartialArtID,
			&i.Title,
			&i.Date,
			&i.Location,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (martial_art_id, title, date, location, description, url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, martial_art_id, title, date, location, description
`

type InsertEventParams struct {
	Column1 sql.NullInt32
	Column2 sql.NullString
	Column3 sql.NullTime
	Column4 sql.NullString
	Column5 sql.NullString
	Column6 sql.NullString
}

type InsertEventRow struct {
	ID           int32
	MartialArtID int32
	Title        string
	Date         sql.NullTime
	Location     sql.NullString
	Description  sql.NullString
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var i InsertEventRow
	err := row.Scan(
		&i.ID,
		&i.MartialArtID,
		&i.Title,
		&i.Date,
		&i.Location,
		&i.Description,
	)
	return i, err
}
