// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const fetchFeed = `-- name: FetchFeed :many
SELECT n.id, n.event_id, n.martial_art_id, n.title, n.content, n.published_at
FROM news_items AS n
JOIN subscriptions AS s
  ON s.martial_art_id = n.martial_art_id
WHERE s.user_id = $1
ORDER BY n.published_at DESC
LIMIT 50
`

type FetchFeedRow struct {
	ID           int32
	EventID      sql.NullInt32
	MartialArtID int32
	Title        string
	Content      string
	PublishedAt  time.Time
}

// $1 = current user's UUID
func (q *Queries) FetchFeed(ctx context.Context, dollar_1 uuid.NullUUID) ([]FetchFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchFeed, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchFeedRow
	for rows.Next() {
		var i FetchFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MartialArtID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
