// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const fetchFeed = `-- name: FetchFeed :many
(
  SELECT
    'news' AS item_type,
    n.id          AS item_id,
    n.title       AS title,
    n.content     AS content,
    n.published_at AS created_at
  FROM news_items n
  JOIN subscriptions s
    ON s.martial_art_id = n.martial_art_id
  WHERE s.user_id = $1
)
UNION ALL
(
  SELECT
    'comment' AS item_type,
    c.id       AS item_id,
    NULL       AS title,         -- comments don’t have titles
    c.content  AS content,
    c.created_at
  FROM comments c
  JOIN follows f
    ON f.followed_id = c.user_id
  WHERE f.follower_id = $1
)
ORDER BY created_at DESC
LIMIT 20
`

type FetchFeedRow struct {
	ItemType  sql.NullString
	ItemID    sql.NullInt32
	Title     sql.NullString
	Content   sql.NullString
	CreatedAt sql.NullTime
}

// $1 = current user's UUID
func (q *Queries) FetchFeed(ctx context.Context, dollar_1 uuid.NullUUID) ([]FetchFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchFeed, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchFeedRow
	for rows.Next() {
		var i FetchFeedRow
		if err := rows.Scan(
			&i.ItemType,
			&i.ItemID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
