// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: follows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFollow = `-- name: CreateFollow :one
WITH p AS(
    SELECT
    $1::UUID AS follower_id,
    $2::UUID AS followed_id
)
INSERT INTO follows (follower_id, followed_id)
SELECT follower_id, followed_id FROM p
ON CONFLICT (follower_id, followed_id) DO NOTHING
RETURNING follower_id, followed_id
`

type CreateFollowParams struct {
	Column1 uuid.NullUUID
	Column2 uuid.NullUUID
}

type CreateFollowRow struct {
	FollowerID uuid.UUID
	FollowedID uuid.UUID
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (CreateFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFollow, arg.Column1, arg.Column2)
	var i CreateFollowRow
	err := row.Scan(&i.FollowerID, &i.FollowedID)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows WHERE follower_id = $1 AND followed_id = $2
`

type DeleteFollowParams struct {
	Column1 uuid.NullUUID
	Column2 uuid.NullUUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.Column1, arg.Column2)
	return err
}
