// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ma.sql

package database

import (
	"context"
)

const getMartialArts = `-- name: GetMartialArts :many
SELECT id, name FROM martial_arts
`

func (q *Queries) GetMartialArts(ctx context.Context) ([]MartialArt, error) {
	rows, err := q.db.QueryContext(ctx, getMartialArts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MartialArt
	for rows.Next() {
		var i MartialArt
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
