// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: news_items.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getAllNews = `-- name: GetAllNews :many
SELECT id, event_id, martial_art_id, title, content, published_at FROM news_items
WHERE published_at >= NOW() - INTERVAL '7 days'
ORDER BY published_at DESC
`

type GetAllNewsRow struct {
	ID           int32
	EventID      sql.NullInt32
	MartialArtID int32
	Title        string
	Content      string
	PublishedAt  time.Time
}

func (q *Queries) GetAllNews(ctx context.Context) ([]GetAllNewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNewsRow
	for rows.Next() {
		var i GetAllNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MartialArtID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsByEvent = `-- name: GetNewsByEvent :many
SELECT id, event_id, martial_art_id, title, content, published_at FROM news_items
WHERE event_id = $1 AND published_at >= NOW() - INTERVAL '7 days'
ORDER BY published_at DESC
`

type GetNewsByEventRow struct {
	ID           int32
	EventID      sql.NullInt32
	MartialArtID int32
	Title        string
	Content      string
	PublishedAt  time.Time
}

func (q *Queries) GetNewsByEvent(ctx context.Context, dollar_1 sql.NullInt32) ([]GetNewsByEventRow, error) {
	rows, err := q.db.QueryContext(ctx, getNewsByEvent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewsByEventRow
	for rows.Next() {
		var i GetNewsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MartialArtID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsByMartialArt = `-- name: GetNewsByMartialArt :many
SELECT id, event_id, martial_art_id, title, content, published_at FROM news_items
WHERE martial_art_id = $1 AND published_at >= NOW() - INTERVAL '7 days'
ORDER BY published_at DESC
`

type GetNewsByMartialArtRow struct {
	ID           int32
	EventID      sql.NullInt32
	MartialArtID int32
	Title        string
	Content      string
	PublishedAt  time.Time
}

func (q *Queries) GetNewsByMartialArt(ctx context.Context, dollar_1 sql.NullInt32) ([]GetNewsByMartialArtRow, error) {
	rows, err := q.db.QueryContext(ctx, getNewsByMartialArt, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewsByMartialArtRow
	for rows.Next() {
		var i GetNewsByMartialArtRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MartialArtID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
