// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: news_items.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const getAllNews = `-- name: GetAllNews :many
SELECT id, event_id, martial_art_id, title, content, published_at FROM news_items
ORDER BY published_at DESC
`

type GetAllNewsRow struct {
	ID           int32
	EventID      sql.NullInt32
	MartialArtID int32
	Title        string
	Content      string
	PublishedAt  time.Time
}

func (q *Queries) GetAllNews(ctx context.Context) ([]GetAllNewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNewsRow
	for rows.Next() {
		var i GetAllNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MartialArtID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsByMartialArt = `-- name: GetNewsByMartialArt :many
SELECT id, event_id, martial_art_id, title, content, published_at FROM news_items
WHERE martial_art_id = $1
ORDER BY published_at DESC
`

type GetNewsByMartialArtRow struct {
	ID           int32
	EventID      sql.NullInt32
	MartialArtID int32
	Title        string
	Content      string
	PublishedAt  time.Time
}

func (q *Queries) GetNewsByMartialArt(ctx context.Context, dollar_1 sql.NullInt32) ([]GetNewsByMartialArtRow, error) {
	rows, err := q.db.QueryContext(ctx, getNewsByMartialArt, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewsByMartialArtRow
	for rows.Next() {
		var i GetNewsByMartialArtRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.MartialArtID,
			&i.Title,
			&i.Content,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNewsItem = `-- name: InsertNewsItem :one
INSERT INTO news_items (event_id, martial_art_id, title, content, published_at, url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, martial_art_id, title, content, published_at
`

type InsertNewsItemParams struct {
	Column1 sql.NullInt32
	Column2 sql.NullInt32
	Column3 sql.NullString
	Column4 sql.NullString
	Column5 sql.NullTime
	Column6 sql.NullString
}

type InsertNewsItemRow struct {
	ID           int32
	EventID      sql.NullInt32
	MartialArtID int32
	Title        string
	Content      string
	PublishedAt  time.Time
}

func (q *Queries) InsertNewsItem(ctx context.Context, arg InsertNewsItemParams) (InsertNewsItemRow, error) {
	row := q.db.QueryRowContext(ctx, insertNewsItem,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var i InsertNewsItemRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.MartialArtID,
		&i.Title,
		&i.Content,
		&i.PublishedAt,
	)
	return i, err
}
